@startuml iniciarSesion
skinparam style strictuml
hide empty members

actor Usuario
participant "LoginView" as View
participant "IniciarSesionController" as Controller
participant "UsuarioRepository" as Repository
participant "Sesion" as Sesion

Usuario -> View: iniciarSesion()
View -> Controller: autenticar(usuario, contraseña)
Controller -> Repository: validarCredenciales(usuario, contraseña)
Repository --> Controller: usuario
Controller -> Sesion: <<create>> crearSesion(usuario)
Sesion --> Controller: sesion
Controller --> View: ok
View --> Usuario: abrirPanelPrincipal()
@enduml
