@startuml abrirInvestigadores-analisis
skinparam backgroundColor white
skinparam shadowing false
skinparam DefaultFontColor black
skinparam DefaultFontSize 12
skinparam linetype polyline

rectangle #CDEBA5 "Navegación Sistema" as NavegacionSistema
rectangle #CDEBA5 "INVESTIGADORES_ABIERTOS" as InvestigadoresAbiertas

package abrirInvestigadores as "abrirInvestigadores()" {
    rectangle #629EF9 ListarInvestigadoresView
    rectangle #b5bd68 InvestigadorController
    rectangle #F2AC4E InvestigadorRepository
    rectangle #F2AC4E Investigador
}

rectangle #CDEBA5 ":Collaboration AbrirInvestigador" as AbrirInvestigador
rectangle #CDEBA5 ":Collaboration CrearInvestigador" as CrearInvestigador
rectangle #CDEBA5 ":Collaboration AbrirPanelPrincipal" as AbrirPanelPrincipal

NavegacionSistema -r-> ListarInvestigadoresView: abrirInvestigadores()

ListarInvestigadoresView -d-> InvestigadorController: listarInvestigadores() : List<Investigador>
InvestigadorController -d-> InvestigadorRepository: obtenerTodos() : List<Investigador>
InvestigadorRepository -- Investigador

ListarInvestigadoresView ..> AbrirInvestigador: abrirInvestigador(investigadorId)
ListarInvestigadoresView ..> CrearInvestigador: crearInvestigador()
ListarInvestigadoresView ..> AbrirPanelPrincipal: abrirPanelPrincipal()

ListarInvestigadoresView ..> InvestigadoresAbiertas: <<finalizar>>

@enduml
