@startuml crearProyecto-analisis
skinparam backgroundColor white
skinparam shadowing false
skinparam DefaultFontColor black
skinparam DefaultFontSize 12
skinparam linetype polyline

rectangle #CDEBA5 "PROYECTOS_ABIERTOS" as ProyectosAbiertos
rectangle #CDEBA5 "PROYECTO_ABIERTO" as ProyectoAbierto

package crearProyecto as "crearProyecto()" {
    rectangle #629EF9 CrearProyectoView
    rectangle #b5bd68 ProyectoController
    rectangle #F2AC4E ProyectoRepository
    rectangle #F2AC4E Proyecto
}

ProyectosAbiertos -r-> CrearProyectoView: crearProyecto()

CrearProyectoView -d-> ProyectoController: crear(titulo, estado, f_inicio, f_fin, descripcion) : Proyecto
ProyectoController -r-> Proyecto: <<create>>
ProyectoController -d-> ProyectoRepository: guardar(proyecto)

CrearProyectoView ..> ProyectoAbierto: <<finalizar>> abrirProyecto(proyecto)
CrearProyectoView ..> ProyectosAbiertos: <<cancelar>> abrirProyectos()

@enduml
