@startuml abrirOpcionesPerfil-diseño
skinparam style strictuml

actor "Usuario" as user
participant "OpcionesPerfilView" as view
participant "OpcionesPerfilController" as controller
participant "Sesion" as sesion
participant "UsuarioRepository" as repo

user -> view : abrirOpcionesPerfil()
activate view
view -> controller : cargarDatosPerfil()
activate controller
controller -> sesion : getUsuarioActual()
activate sesion
sesion --> controller : usuarioId
deactivate sesion
controller -> repo : obtenerPerfilId(usuarioId)
activate repo
repo --> controller : DatosPerfil
deactivate repo
controller --> view : DatosPerfil
deactivate controller
view --> user : mostrarOpcionesPerfil()
deactivate view
@enduml
