@startuml responderPublicacion-analisis
skinparam backgroundColor white
skinparam shadowing false
skinparam DefaultFontColor black
skinparam DefaultFontSize 12
skinparam linetype polyline

rectangle #CDEBA5 "PUBLICACION_ABIERTA" as PublicacionAbierta

package responderPublicacion as "responderPublicacion()" {
    rectangle #629EF9 <<Boundary>> ResponderPublicacionView
    rectangle #b5bd68 <<Control>> PublicacionController
    rectangle #F2AC4E <<Entity>> PublicacionRepository
    rectangle #F2AC4E <<Entity>> Publicacion
    rectangle #F2AC4E <<Entity>> Sesion
}

PublicacionAbierta -r-> ResponderPublicacionView: responderPublicacion(publicacionPadreId)

ResponderPublicacionView -d-> PublicacionController: enviarRespuesta(contenido) : boolean
PublicacionController -d-> Sesion: getUsuarioActual() : Usuario
PublicacionController -r-> Publicacion: <<create>> (contenido, autor, padreId)
PublicacionController -d-> PublicacionRepository: guardar(respuesta) : boolean

ResponderPublicacionView ..> PublicacionAbierta: <<finalizar>>
ResponderPublicacionView ..> PublicacionAbierta: <<cancelar>>

@enduml
