@startuml
skinparam style strictuml
actor Investigador
boundary ListarConvocatoriasView <<boundary>>
control ConvocatoriaController <<control>>
entity ConvocatoriaRepository <<entity>>
database Database <<database>>

Investigador -> ListarConvocatoriasView : abrirConvocatorias()
activate ListarConvocatoriasView
ListarConvocatoriasView -> ConvocatoriaController : listarConvocatorias()
activate ConvocatoriaController
ConvocatoriaController -> ConvocatoriaRepository : obtenerTodas()
activate ConvocatoriaRepository
ConvocatoriaRepository -> Database : select * from convocatorias
activate Database
Database --> ConvocatoriaRepository : listaConvocatorias
deactivate Database
ConvocatoriaRepository --> ConvocatoriaController : listaConvocatorias
deactivate ConvocatoriaRepository
ConvocatoriaController --> ListarConvocatoriasView : listaConvocatorias
deactivate ConvocatoriaController
ListarConvocatoriasView --> Investigador : mostrarLista(listaConvocatorias)
deactivate ListarConvocatoriasView
@enduml
