@startuml editarPublicacion-analisis
skinparam backgroundColor white
skinparam shadowing false
skinparam DefaultFontColor black
skinparam DefaultFontSize 12
skinparam linetype polyline

rectangle #CDEBA5 "MI_PUBLICACION_ABIERTA" as MiPublicacionAbierta

package editarPublicacion as "editarPublicacion()" {
    rectangle #629EF9 <<Boundary>> EditarPublicacionView
    rectangle #b5bd68 <<Control>> PublicacionController
    rectangle #F2AC4E <<Entity>> PublicacionRepository
    rectangle #F2AC4E <<Entity>> Publicacion
}

MiPublicacionAbierta -r-> EditarPublicacionView: editarPublicacion()

EditarPublicacionView -d-> PublicacionController: cargarDatosActuales()
PublicacionController -d-> PublicacionRepository: obtenerPorId(publicacionId) : Publicacion

EditarPublicacionView -d-> PublicacionController: guardarCambios(datosNuevos) : boolean
PublicacionController -d-> PublicacionRepository: actualizar(publicacion) : boolean

EditarPublicacionView ..> MiPublicacionAbierta: <<finalizar>> confirmar()
EditarPublicacionView ..> MiPublicacionAbierta: <<cancelar>> cancelar()

@enduml
