@startuml abrirPanelPrincipal-diseño
skinparam style strictuml

actor "Usuario" as user
participant "PanelPrincipalView" as view
participant "PanelPrincipalController" as controller
participant "Sesion" as sesion
participant "PermisosRepository" as repo
participant "OpcionesMenu" as menu

user -> view : abrirPanelPrincipal()
activate view 
view -> controller : abrirPanelPrincipal()
activate controller
controller -> sesion : getUsuarioActual()
activate sesion
sesion --> controller : usuario
deactivate sesion
controller -> repo : obtenerOpciones(usuario)
activate repo
repo --> controller : List<Opcion>
deactivate repo
controller -> menu : crearPanelPrincipal(List<Opcion>)
activate menu
menu --> controller : PanelPrincipal
deactivate menu
controller --> view : PanelPrincipal
deactivate controller
view --> user : mostrarPanelPrincipal(PanelPrincipal)
deactivate view
@enduml
