@startuml abrirPanelPrincipal-diseño
skinparam style strictuml

actor "Usuario" as user
participant "PanelPrincipalView" as view
participant "PanelPrincipalController" as controller
participant "Sesion" as sesion
participant "PermisosRepository" as repo
participant "OpcionesMenu" as menu

user -> view : abrirPanelPrincipal()
activate view 
view -> controller : inicializarPanel()
activate controller
controller -> sesion : getUsuarioActual()
activate sesion
sesion --> controller : usuario
deactivate sesion
controller -> repo : obtenerOpcionesDisponibles(usuario)
activate repo
repo --> controller : List<Opcion>
deactivate repo
controller -> menu : crearMenu(List<Opcion>)
activate menu
menu --> controller : instanciaOpcionesMenu
deactivate menu
controller --> view : OpcionesMenu
deactivate controller
view --> user : mostrarPanelPrincipal()
deactivate view
@enduml
