@startuml abrirSolicitudesEliminacionPerfil-analisis
skinparam backgroundColor white
skinparam shadowing false
skinparam DefaultFontColor black
skinparam DefaultFontSize 12
skinparam linetype polyline

rectangle #CDEBA5 "OPCIONES_PERFIL_ABIERTO" as OpcionesPerfilAbierto
rectangle #CDEBA5 "SOLICITUDES_ELIMINACION_PERFIL_ABIERTAS" as SolicitudesAbiertas

package abrirSolicitudesEliminacionPerfil as "abrirSolicitudesEliminacionPerfil()" {
    rectangle #629EF9 <<Boundary>> ListarSolicitudesView
    rectangle #b5bd68 <<Control>> PerfilController
    rectangle #F2AC4E <<Entity>> SolicitudEliminacionRepository
    rectangle #F2AC4E <<Entity>> SolicitudEliminacion
}

rectangle #CDEBA5 ":Collaboration AbrirSolicitudEliminacionPerfil" as AbrirSolicitud
rectangle #CDEBA5 ":Collaboration AbrirOpcionesPerfil" as AbrirOpcionesPerfil

OpcionesPerfilAbierto -r-> ListarSolicitudesView: abrirSolicitudesEliminacionPerfil()

ListarSolicitudesView -d-> PerfilController: listarSolicitudesPendientes() : List<SolicitudEliminacion>
PerfilController -d-> SolicitudEliminacionRepository: obtenerTodasPendientes() : List<SolicitudEliminacion>
SolicitudEliminacionRepository -- SolicitudEliminacion

ListarSolicitudesView ..> AbrirSolicitud: abrirSolicitudEliminacionPerfil(solicitudId)
ListarSolicitudesView ..> AbrirOpcionesPerfil: abrirOpcionesPerfil()

ListarSolicitudesView ..> SolicitudesAbiertas: <<finalizar>>

@enduml
