@startuml solicitarEliminacionPerfil-analisis
skinparam backgroundColor white
skinparam shadowing false
skinparam DefaultFontColor black
skinparam DefaultFontSize 12
skinparam linetype polyline

rectangle #CDEBA5 "OPCIONES_PERFIL_ABIERTO" as OpcionesPerfilAbierto
rectangle #CDEBA5 "SESION_CERRADA" as SesionCerrada

package solicitarEliminacionPerfil as "solicitarEliminacionPerfil()" {
    rectangle #629EF9 <<Boundary>> SolicitarEliminacionView
    rectangle #b5bd68 <<Control>> PerfilController
    rectangle #F2AC4E <<Entity>> SolicitudEliminacionRepository
    rectangle #F2AC4E <<Entity>> SolicitudEliminacion
    rectangle #F2AC4E <<Entity>> Sesion
}

OpcionesPerfilAbierto -r-> SolicitarEliminacionView: solicitarEliminacionPerfil()

SolicitarEliminacionView -d-> PerfilController: crearSolicitudEliminacion()
PerfilController -d-> Sesion: getUsuarioActual() : Usuario
PerfilController -r-> SolicitudEliminacion: <<create>>
PerfilController -d-> SolicitudEliminacionRepository: guardar(solicitud)

SolicitarEliminacionView ..> SesionCerrada: <<finalizar>> confirmar()
SolicitarEliminacionView ..> OpcionesPerfilAbierto: <<cancelar>> cancelar()

@enduml
