@startuml abrirProyecto-analisis
skinparam backgroundColor white
skinparam shadowing false
skinparam DefaultFontColor black
skinparam DefaultFontSize 12
skinparam linetype polyline

rectangle #CDEBA5 "PROYECTOS_ABIERTOS" as ProyectosAbiertos
rectangle #CDEBA5 "PROYECTO_ABIERTO" as ProyectoAbierto

package abrirProyecto as "abrirProyecto()" {
    rectangle #629EF9 DetalleProyectoView
    rectangle #b5bd68 ProyectoController
    rectangle #F2AC4E ProyectoRepository
    rectangle #F2AC4E Proyecto
    rectangle #F2AC4E Investigador
}

rectangle #CDEBA5 ":Collaboration EditarProyecto" as EditarProyecto
rectangle #CDEBA5 ":Collaboration EliminarProyecto" as EliminarProyecto
rectangle #CDEBA5 ":Collaboration AbrirEntregables" as AbrirEntregables
rectangle #CDEBA5 ":Collaboration AgregarInvestigador" as AgregarInvestigador
rectangle #CDEBA5 ":Collaboration AbrirInvestigadores" as AbrirInvestigadores
rectangle #CDEBA5 ":Collaboration AbrirProyectos" as AbrirProyectos

ProyectosAbiertos -r-> DetalleProyectoView: abrirProyecto(proyectoId)

DetalleProyectoView -d-> ProyectoController: obtenerDetalleProyecto(proyectoId) : Proyecto
ProyectoController -d-> ProyectoRepository: obtenerPorId(proyectoId) : Proyecto
ProyectoRepository -- Proyecto
Proyecto -- Investigador

DetalleProyectoView ..> EditarProyecto: editarProyecto()
DetalleProyectoView ..> EliminarProyecto: eliminarProyecto()
DetalleProyectoView ..> AbrirEntregables: abrirEntregables()
DetalleProyectoView ..> AgregarInvestigador: agregarInvestigador()
DetalleProyectoView ..> AbrirInvestigadores: abrirInvestigadores()
DetalleProyectoView ..> AbrirProyectos: abrirProyectos()

DetalleProyectoView ..> ProyectoAbierto: <<finalizar>>

@enduml
