@startuml eliminarInvestigador-analisis
skinparam backgroundColor white
skinparam shadowing false
skinparam DefaultFontColor black
skinparam DefaultFontSize 12
skinparam linetype polyline

rectangle #CDEBA5 "PROYECTO_ABIERTO" as ProyectoAbierto

package eliminarInvestigador as "eliminarInvestigador()" {
    rectangle #629EF9 <<Boundary>> EliminarInvestigadorView
    rectangle #b5bd68 <<Control>> ProyectoController
    rectangle #F2AC4E <<Entity>> ProyectoRepository
    rectangle #F2AC4E <<Entity>> Proyecto
    rectangle #F2AC4E <<Entity>> Investigador
}

ProyectoAbierto -r-> EliminarInvestigadorView: eliminarInvestigador(investigadorId)

EliminarInvestigadorView -d-> ProyectoController: solicitarConfirmacionEliminacion()

EliminarInvestigadorView -d-> ProyectoController: confirmarDesvinculacion(proyectoId, investigadorId)
ProyectoController -d-> ProyectoRepository: eliminarAsociacion(proyectoId, investigadorId)

EliminarInvestigadorView ..> ProyectoAbierto: <<finalizar>>
EliminarInvestigadorView ..> ProyectoAbierto: <<cancelar>>

@enduml
